products = [(1, "Pen", 2),
            (2, "Notebook", 5),
            (3, "Calculator", 9),
            (4, "Backpack", 45),
            (5, "Alarm clock", 8),
            (6, "Water bottle", 3),
            (7, "Headphones", 20),
            (8, "Laptop", 1500),
            (9, "Pencil case", 4),
            (10, "Highlighter set", 3),
            (11, "Desk lamp", 15),
            (12, "Ruler", 1),
            (13, "Tape dispenser", 2),
            (14, "USB flash drive", 8),
            (15, "Coffee mug", 3),
            (16, "Stapler", 4),
            (17, "Scissors", 2),
            (18, "Calendar", 7),
            (19, "External hard drive", 60),
            (20, "Mouse pad", 2),
            (21, "Whiteboard markers", 5),
            (22, "Eraser", 1),
            (23, "Bookshelf", 80),
            (24, "Sunglasses", 12),
            (25, "Portable charger", 20),
            (26, "Folder set", 6),
            (27, "Drawing tablet", 200),
            (28, "Post-it notes", 3),
            (29, "Wall clock", 15),
            (30, "Power cord", 10)]
